### ISSUE TITLE
Hi just wanna ask something about this repo

### ISSUE THREAD

**Issue by mzcoder-hub** [ThaddeusJiang/react-sortable-list#2]
hi are this react-sortable-list is support nextjs & horizontal sortable ?

**Comment by ThaddeusJiang** [comment]
@mzcoder-hub Of course, it is supported.

**Comment by mzcoder-hub** [comment]
> 

i would like to try in follow back my twitter btw :p mazgalangcom

**Comment by ThaddeusJiang** [comment]
> > 
> 
> @ThaddeusJiang i would like to try it thank for your reply, follow back my twitter btw :p mazgalangcom, did you have example for horizontal sortable ?

Hi @mzcoder-hub 
I have made a horizontal sortable list example

```diff
export const HorizontalExample: React.VFC = () => {
  const [items, setItems] = useState<SortableItemProps[]>([
    { id: '1', name: 'Item 1' },
    { id: '2', name: 'Item 2' },
    { id: '3', name: 'Item 3' },
  ]);
  return (
    <div className="flex space-x-4">
      <SortableList
        items={items}
        setItems={setItems}
        itemRender={({ item }: ItemRenderProps) => <Item name={item.name} />}
+        horizontal
      />
    </div>
  );
};
```

https://github.com/ThaddeusJiang/react-sortable-list#use-case-4-horizontal-sortable-list

![CleanShot 2022-09-07 at 17 03 42](https://user-images.githubusercontent.com/17308201/188824987-4a833fd4-2bd3-41db-b656-f838b956b5b7.gif)

**Comment by ThaddeusJiang** [comment]
Hi @mzcoder-hub 
This library has been migrated to https://github.com/ThaddeusJiang/omakase-ui/tree/main/packages/react-sortable-list，see you later.
