### ISSUE TITLE
Drag on/off functionality

### ISSUE THREAD

**Issue by webmastervishal** [ThaddeusJiang/react-sortable-list#4]
Hey, I was using react-sortable-list in one of my projects where I was having a requirement to turn drag on/off.

There should be an `enabled` prop where we can control whether we want to enable the drag-drop feature or not.

**Comment by ThaddeusJiang** [comment]
@webmastervishal Good idea.
But, why not render a plain list instead?

Just like: 

```diff
+ export const ItemRenderExample: React.VFC = ({ sortable }: { sortable: boolean}) => {
  const [items, setItems] = useState<SortableItemProps[]>([
    { id: '1', name: 'Item 1' },
    { id: '2', name: 'Item 2' },
    { id: '3', name: 'Item 3' },
  ]);

+  if(!sortable) {
+    return (
+         <>
+          {items.map(item => (
+            <div key={item.id} className="w-1/2 h-10 m-8 bg-blue-400 text-center">
+              {item.name}
+            </div>
+          ))}          
+        </>
+    )
+  }

  return (
    <SortableList
      items={items}
      setItems={setItems}
      itemRender={({ item }: ItemRenderProps) => (
        <div className="w-1/2 h-10 m-8 bg-blue-400 text-center">
          {item.name}
        </div>
      )}
    />
  );
};
```

**Comment by webmastervishal** [comment]
> @webmastervishal Good idea. But, why not render a plain list instead?
> 
> Just like:
> 
> ```diff
> + export const ItemRenderExample: React.VFC = ({ sortable }: { sortable: boolean}) => {
>   const [items, setItems] = useState<SortableItemProps[]>([
>     { id: '1', name: 'Item 1' },
>     { id: '2', name: 'Item 2' },
>     { id: '3', name: 'Item 3' },
>   ]);
> 
> +  if(!sortable) {
> +    return (
> +         <>
> +          {items.map(item => (
> +            <div key={item.id} className="w-1/2 h-10 m-8 bg-blue-400 text-center">
> +              {item.name}
> +            </div>
> +          ))}          
> +        </>
> +    )
> +  }
> 
>   return (
>     <SortableList
>       items={items}
>       setItems={setItems}
>       itemRender={({ item }: ItemRenderProps) => (
>         <div className="w-1/2 h-10 m-8 bg-blue-400 text-center">
>           {item.name}
>         </div>
>       )}
>     />
>   );
> };
> ```

Yep, currently, I am doing the same thing. 
But if you see we are adding some extra code to do that. 
If we can just control with a prop, and drag on/off it would be good. 

The above-given logic needs to be implemented by this plugin, or else every user will have to do it again and again.

**Comment by ThaddeusJiang** [comment]
@webmastervishal I see.
Let's do it.

**Comment by ThaddeusJiang** [comment]
Hi @webmastervishal I have published the new version,

Usage

```diff
export const ItemRenderExample: React.VFC = () => {
  const [items, setItems] = useState<SortableItemProps[]>([
    { id: '1', name: 'Item 1' },
    { id: '2', name: 'Item 2' },
    { id: '3', name: 'Item 3' },
  ]);
  return (
    <SortableList
+     disabled
      items={items}
      setItems={setItems}
      itemRender={({ item }: ItemRenderProps) => (
        <div className="w-1/2 h-10 m-8 bg-blue-400 text-center">
          {item.name}
        </div>
      )}
    />
  );
};
```
