### ISSUE TITLE
Doesnt seem working when dragging + scrolling

### ISSUE THREAD

**Issue by vincentwinkel** [ThaddeusJiang/react-sortable-list#6]
When I drag then scroll (on Macbook), the selected item doesn't follow the mouse.

I literally copy/pasted the example in the README and tied it out with 30 items in a box.

**Comment by ThaddeusJiang** [comment]
I'm very sorry, I had to take care of some family matters earlier.
I will check on this issue within the week.

**Comment by Tobo7** [comment]
Updating the `dnd-kit` libraries to the latest version solved the issue for me. So I had to copy out the library to my project. Fortunately the library has only two files  (`SortableItem`, `SortableList`).

**Comment by ThaddeusJiang** [comment]
@Tobo7 Thank you for your feedback, I have upgraded dndkit.
